try{
    throw "user not found"
}catch(err){
    console.log(err);
}finally{

}